sonar.projectKey=AnaharaYasuo_realestate_crawler
sonar.organization=anaharayasuo

# Path to the source code
sonar.sources=src

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Python version
sonar.python.version=3.11

# Exclusions
sonar.exclusions=**/tests/**,**/migrations/**,**/Temp/**,**/logs/**,**/catboost_info/**,**/.pytest_cache/**,**/docs/**,**/*.joblib,**/ml/models/**,**/ml/data/**,**/*.csv,**/*.png,**/*.jpg,**/*.jpeg
sonar.cpd.exclusions=**/migrations/**

# Tests & Coverage
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest-report.xml
