# Daiwa House Selectors Configuration
mansion:
  title: "h1"
  price: ".price"
  table:
    header: "th"
    value: "td"
  field_mappings:
    所在地: address
    価格: priceStr
    間取り: madori
    専有面積: senyuMensekiStr
    築年月／完成予定年月: chikunengetsuStr
    所在階: kaisuStr
    建物構造: kouzou
    管理形態: kanriKeitai
    管理費: kanrihiStr
    修繕積立金: syuzenTsumitateStr
    総戸数: soukosuStr
    土地権利: tochikenri
    現況: genkyo
    取引態様: torihiki

kodate:
  title: "h1"
  price: ".price"
  table:
    header: "th"
    value: "td"
  field_mappings:
    所在地: address
    価格: priceStr
    間取り: madori
    築年月／完成予定年月: chikunengetsuStr
    建物構造: kouzou
    階数: kaisuStr
    土地面積: tochiMensekiStr
    建物面積: tatemonoMensekiStr
    建ぺい率: kenpeiStr
    容積率: yousekiStr
    用途地域: youtoChiiki
    都市計画: kuiki
    接道状況: setsudou
    土地権利: tochikenri
    現況: genkyo
    取引態様: torihiki

tochi:
  title: "h1"
  price: ".price"
  table:
    header: "th"
    value: "td"
  field_mappings:
    所在地: address
    価格: priceStr
    土地面積: tochiMensekiStr
    建ぺい率: kenpeiStr
    容積率: yousekiStr
    用途地域: youtoChiiki
    都市計画: kuiki
    接道状況: setsudou
    地目: chimoku
    土地権利: tochikenri
    現況: genkyo
    取引態様: torihiki
