mansion:
  title: "td.prg-nameTableItem"
  price: "td.prg-priceTableItem"
  root_xpath: "//a[contains(@href, '/chuko/mansion/')]/@href"

kodate:
  title: "td.prg-nameTableItem"
  price: "td.prg-priceTableItem"
  root_xpath: "//a[contains(@href, '/chuko/kodate/')]/@href"

investmentapartment:
  title: "td.prg-nameTableItem"
  price: "td.prg-priceTableItem"
  root_xpath: "//a[contains(@href, '/toushi/')]/@href"

tochi:
  title: "td.prg-nameTableItem"
  price: "td.prg-priceTableItem"

