# Generated by Django 5.2.10 on 2026-02-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitsuiinvestmentapartment',
            name='soukosuStr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='mitsuiinvestmentapartment',
            name='tatemonoMensekiStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='mitsuiinvestmentapartment',
            name='tochiMensekiStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='mitsuiinvestmentkodate',
            name='tatemonoMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mitsuiinvestmentkodate',
            name='tochiMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sumifuinvestmentapartment',
            name='kenpeiStr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sumifuinvestmentapartment',
            name='soukosuStr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='sumifuinvestmentapartment',
            name='tatemonoMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sumifuinvestmentapartment',
            name='tochiMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sumifuinvestmentapartment',
            name='yousekiStr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sumifuinvestmentkodate',
            name='kenpeiStr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sumifuinvestmentkodate',
            name='tatemonoMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sumifuinvestmentkodate',
            name='tochiMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tokyuinvestmentapartment',
            name='kenpeiStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tokyuinvestmentapartment',
            name='soukosuStr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='tokyuinvestmentapartment',
            name='tatemonoMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tokyuinvestmentapartment',
            name='tochiMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tokyuinvestmentapartment',
            name='yousekiStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tokyuinvestmentkodate',
            name='kenpeiStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tokyuinvestmentkodate',
            name='tatemonoMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tokyuinvestmentkodate',
            name='tochiMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tokyuinvestmentkodate',
            name='yousekiStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentapartment',
            name='kenpeiStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentapartment',
            name='yousekiStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentkodate',
            name='kenpeiStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentkodate',
            name='yousekiStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='misawakodate',
            name='kenpeiStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='misawakodate',
            name='tatemonoMenseki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='misawakodate',
            name='tatemonoMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='misawakodate',
            name='tochiMenseki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='misawakodate',
            name='tochiMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='misawakodate',
            name='yousekiStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='misawamansion',
            name='balconyMenseki',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='misawamansion',
            name='balconyMensekiStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='misawamansion',
            name='kenpeiStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='misawamansion',
            name='senyuMenseki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='misawamansion',
            name='senyuMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='misawamansion',
            name='yousekiStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='misawatochi',
            name='kenpeiStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='misawatochi',
            name='tochiMenseki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='misawatochi',
            name='tochiMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='misawatochi',
            name='yousekiStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='tatemonoMenseki',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='tochiMenseki',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentkodate',
            name='tatemonoMenseki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentkodate',
            name='tochiMenseki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nomurakodate',
            name='kenpei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomurakodate',
            name='kenpeiStr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='nomurakodate',
            name='tatemonoMenseki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nomurakodate',
            name='tatemonoMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='nomurakodate',
            name='tochiMenseki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nomurakodate',
            name='tochiMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='nomurakodate',
            name='youseki',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomurakodate',
            name='yousekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='nomuramansion',
            name='senyuMenseki',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nomuramansion',
            name='senyuMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='nomuratochi',
            name='kenpei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomuratochi',
            name='kenpeiStr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='nomuratochi',
            name='tochiMenseki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nomuratochi',
            name='tochiMensekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='nomuratochi',
            name='youseki',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomuratochi',
            name='yousekiStr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentapartment',
            name='tatemonoMenseki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentapartment',
            name='tochiMenseki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentkodate',
            name='tatemonoMenseki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentkodate',
            name='tochiMenseki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='tatemonoMenseki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='tochiMenseki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentkodate',
            name='tatemonoMenseki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentkodate',
            name='tochiMenseki',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
