# Generated by Django 4.2.7 on 2026-01-10 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokyuKodate',
            fields=[
                ('tokyumansion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='package.tokyumansion')),
                ('tochiMensekiStr', models.TextField()),
                ('tochiMenseki', models.DecimalField(decimal_places=3, max_digits=8)),
                ('tatemonoMensekiStr', models.TextField()),
                ('tatemonoMenseki', models.DecimalField(decimal_places=3, max_digits=8)),
                ('kaisuKouzou', models.TextField()),
                ('chimokuChisei', models.TextField()),
                ('chimoku', models.TextField()),
                ('chisei', models.TextField()),
                ('setsudou', models.TextField()),
                ('douro', models.TextField()),
                ('douroMuki', models.TextField()),
                ('douroHaba', models.DecimalField(decimal_places=3, max_digits=6)),
                ('douroKubun', models.TextField()),
                ('setsumen', models.DecimalField(decimal_places=3, max_digits=6)),
                ('kenpeiYousekiStr', models.TextField()),
                ('kenpei', models.IntegerField()),
                ('youseki', models.IntegerField()),
                ('chiikiChiku', models.TextField()),
                ('kuiki', models.TextField()),
                ('youtoChiiki', models.TextField()),
                ('boukaChiiki', models.TextField()),
                ('saikenchiku', models.TextField()),
                ('sonotaChiiki', models.TextField()),
                ('kokudoHou', models.TextField()),
            ],
            options={
                'db_table': 'tokyu_kodate',
                'abstract': False,
            },
            bases=('package.tokyumansion',),
        ),
        migrations.CreateModel(
            name='TokyuTochi',
            fields=[
                ('tokyumansion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='package.tokyumansion')),
                ('tochiMensekiStr', models.TextField()),
                ('tochiMenseki', models.DecimalField(decimal_places=3, max_digits=8)),
                ('chimokuChisei', models.TextField()),
                ('chimoku', models.TextField()),
                ('chisei', models.TextField()),
                ('setsudou', models.TextField()),
                ('douro', models.TextField()),
                ('douroMuki', models.TextField()),
                ('douroHaba', models.DecimalField(decimal_places=3, max_digits=6)),
                ('douroKubun', models.TextField()),
                ('setsumen', models.DecimalField(decimal_places=3, max_digits=6)),
                ('kenpeiYousekiStr', models.TextField()),
                ('kenpei', models.IntegerField()),
                ('youseki', models.IntegerField()),
                ('chiikiChiku', models.TextField()),
                ('kuiki', models.TextField()),
                ('youtoChiiki', models.TextField()),
                ('boukaChiiki', models.TextField()),
                ('saikenchiku', models.TextField()),
                ('sonotaChiiki', models.TextField()),
                ('kenchikuJoken', models.TextField()),
                ('kokudoHou', models.TextField()),
            ],
            options={
                'db_table': 'tokyu_tochi',
                'abstract': False,
            },
            bases=('package.tokyumansion',),
        ),
    ]
