# Generated by Django 4.2.7 on 2026-01-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_tokyukodate_tokyutochi'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitsuiInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.TextField()),
                ('pageUrl', models.TextField()),
                ('inputDate', models.DateField()),
                ('inputDateTime', models.DateTimeField()),
                ('priceStr', models.TextField()),
                ('price', models.IntegerField()),
                ('address', models.TextField()),
                ('traffic', models.TextField()),
                ('grossYield', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currentStatus', models.TextField()),
                ('structure', models.TextField()),
                ('yearBuilt', models.TextField()),
                ('landArea', models.TextField()),
                ('buildingArea', models.TextField()),
            ],
            options={
                'db_table': 'mitsui_investment',
            },
        ),
        migrations.CreateModel(
            name='SumifuInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.TextField()),
                ('priceStr', models.TextField()),
                ('price', models.IntegerField()),
                ('address', models.TextField()),
                ('traffic', models.TextField()),
                ('grossYield', models.DecimalField(decimal_places=2, max_digits=5)),
                ('landArea', models.TextField()),
                ('buildingArea', models.TextField()),
                ('yearBuilt', models.TextField()),
                ('structure', models.TextField()),
            ],
            options={
                'db_table': 'sumifu_investment',
            },
        ),
    ]
