# Generated by Django 5.2.10 on 2026-02-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_mitsuiinvestmentapartment_kanrihi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumifuinvestmentapartment',
            name='chimoku',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentapartment',
            name='kaisu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentapartment',
            name='kaisuStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentapartment',
            name='kenpei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentapartment',
            name='kenpeiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentapartment',
            name='setsudou',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentapartment',
            name='soukosu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentapartment',
            name='soukosuStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentapartment',
            name='youseki',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentapartment',
            name='yousekiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentapartment',
            name='youtoChiiki',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentkodate',
            name='chimoku',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentkodate',
            name='kenpei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentkodate',
            name='kenpeiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentkodate',
            name='setsudou',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentkodate',
            name='youseki',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentkodate',
            name='yousekiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumifuinvestmentkodate',
            name='youtoChiiki',
            field=models.TextField(blank=True, null=True),
        ),
    ]
