# Generated by Django 4.2.7 on 2026-01-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_mitsuiinvestment_sumifuinvestment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokyuInvestment',
            fields=[
                ('tokyumansion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='package.tokyumansion')),
                ('yield_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('annualIncome', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tokyu_investment',
                'abstract': False,
            },
            bases=('package.tokyumansion',),
        ),
    ]
