# Generated by Django 5.2.10 on 2026-02-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_alter_sumifuinvestmentapartment_chimoku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misawainvestmentapartment',
            name='chikunengetsuStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentapartment',
            name='chimoku',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentapartment',
            name='currentStatus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentapartment',
            name='kenpeiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentapartment',
            name='kouzou',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentapartment',
            name='monthlyRent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentapartment',
            name='setsudou',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentapartment',
            name='soukosu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentapartment',
            name='tatemonoMensekiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentapartment',
            name='tochiMensekiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentapartment',
            name='tochikenri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentapartment',
            name='yousekiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentapartment',
            name='youtoChiiki',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentkodate',
            name='chikunengetsuStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentkodate',
            name='chimoku',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentkodate',
            name='currentStatus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentkodate',
            name='kenpeiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentkodate',
            name='kouzou',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentkodate',
            name='madori',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentkodate',
            name='monthlyRent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentkodate',
            name='setsudou',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentkodate',
            name='tatemonoMensekiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentkodate',
            name='tochiMensekiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentkodate',
            name='tochikenri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentkodate',
            name='yousekiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='misawainvestmentkodate',
            name='youtoChiiki',
            field=models.TextField(blank=True, null=True),
        ),
    ]
