# Generated by Django 5.2.10 on 2026-02-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_alter_misawainvestmentapartment_chikunengetsustr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='annualRent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='chikunengetsuStr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='chimoku',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='currentStatus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='grossYield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='kenpei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='kouzou',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='monthlyRent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='setsudou',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='soukosu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='soukosuStr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='tatemonoMenseki',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='tatemonoMensekiStr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='tochiMenseki',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='tochiMensekiStr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='tochikenri',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='youseki',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentapartment',
            name='youtoChiiki',
            field=models.TextField(blank=True),
        ),
    ]
