# Generated by Django 5.2.10 on 2026-02-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_alter_tokyuinvestmentapartment_annualrent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokyuinvestmentkodate',
            name='kenpei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentkodate',
            name='startRoad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentkodate',
            name='tochikenri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentkodate',
            name='youseki',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokyuinvestmentkodate',
            name='youtoChiiki',
            field=models.TextField(blank=True, null=True),
        ),
    ]
