# Generated by Django 5.2.10 on 2026-02-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_alter_tokyuinvestmentkodate_kenpei_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomurainvestmentapartment',
            name='chimoku',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomurainvestmentapartment',
            name='kenpeiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomurainvestmentapartment',
            name='setsudou',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomurainvestmentapartment',
            name='tochikenri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomurainvestmentapartment',
            name='yousekiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomurainvestmentapartment',
            name='youtoChiiki',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomurainvestmentkodate',
            name='chimoku',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomurainvestmentkodate',
            name='kenpei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomurainvestmentkodate',
            name='kenpeiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomurainvestmentkodate',
            name='setsudou',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomurainvestmentkodate',
            name='tochikenri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomurainvestmentkodate',
            name='youseki',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomurainvestmentkodate',
            name='yousekiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomurainvestmentkodate',
            name='youtoChiiki',
            field=models.TextField(blank=True, null=True),
        ),
    ]
