# Generated by Django 5.2.10 on 2026-02-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0008_alter_nomurainvestmentapartment_chimoku_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomurainvestmentapartment',
            old_name='remarks',
            new_name='biko',
        ),
        migrations.RenameField(
            model_name='nomurainvestmentkodate',
            old_name='remarks',
            new_name='biko',
        ),
        migrations.RenameField(
            model_name='nomurakodate',
            old_name='remarks',
            new_name='biko',
        ),
        migrations.RenameField(
            model_name='nomuramansion',
            old_name='remarks',
            new_name='biko',
        ),
        migrations.RenameField(
            model_name='nomuratochi',
            old_name='remarks',
            new_name='biko',
        ),
        migrations.AddField(
            model_name='nomurainvestmentapartment',
            name='address1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomurainvestmentapartment',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomurainvestmentapartment',
            name='address3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomurainvestmentapartment',
            name='addressKyoto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomurainvestmentkodate',
            name='address1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomurainvestmentkodate',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomurainvestmentkodate',
            name='address3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomurainvestmentkodate',
            name='addressKyoto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomurakodate',
            name='address1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomurakodate',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomurakodate',
            name='address3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomurakodate',
            name='addressKyoto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomuramansion',
            name='address1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomuramansion',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomuramansion',
            name='address3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomuramansion',
            name='addressKyoto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomuratochi',
            name='address1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomuratochi',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomuratochi',
            name='address3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomuratochi',
            name='addressKyoto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
