# Generated by Django 5.2.10 on 2026-02-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0009_rename_remarks_nomurainvestmentapartment_biko_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='misawainvestmentapartment',
            old_name='remarks',
            new_name='biko',
        ),
        migrations.RenameField(
            model_name='misawainvestmentkodate',
            old_name='remarks',
            new_name='biko',
        ),
        migrations.RenameField(
            model_name='misawakodate',
            old_name='remarks',
            new_name='biko',
        ),
        migrations.RenameField(
            model_name='misawamansion',
            old_name='remarks',
            new_name='biko',
        ),
        migrations.RenameField(
            model_name='misawatochi',
            old_name='remarks',
            new_name='biko',
        ),
        migrations.RenameField(
            model_name='mitsuimansion',
            old_name='barukoniMenseki',
            new_name='balconyMenseki',
        ),
        migrations.RenameField(
            model_name='mitsuimansion',
            old_name='barukoniMensekiStr',
            new_name='balconyMensekiStr',
        ),
        migrations.RenameField(
            model_name='nomuramansion',
            old_name='balconyArea',
            new_name='balconyMensekiStr',
        ),
        migrations.RenameField(
            model_name='sumifumansion',
            old_name='barukoniMenseki',
            new_name='balconyMenseki',
        ),
        migrations.RenameField(
            model_name='sumifumansion',
            old_name='barukoniMensekiStr',
            new_name='balconyMensekiStr',
        ),
        migrations.RemoveField(
            model_name='tokyumansion',
            name='cyusyajo',
        ),
        migrations.AddField(
            model_name='nomuramansion',
            name='balconyMenseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
