# Generated by Django 5.2.10 on 2026-02-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_alter_mitsuiinvestmentapartment_chimoku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='chimoku',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='kaisuStr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='kanrihi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='kenpei',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='kenpeiStr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='setsudou',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='soukosu',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='soukosuStr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='syuzenTsumitate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='tatemonoMenseki',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='tatemonoMensekiStr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='tochiMenseki',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='tochiMensekiStr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='tochikenri',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='youseki',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='yousekiStr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentapartment',
            name='youtoChiiki',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentkodate',
            name='chimoku',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentkodate',
            name='kaisuStr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentkodate',
            name='kenpei',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentkodate',
            name='kenpeiStr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentkodate',
            name='setsudou',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentkodate',
            name='tatemonoMensekiStr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentkodate',
            name='tochiMensekiStr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentkodate',
            name='youseki',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentkodate',
            name='yousekiStr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mitsuiinvestmentkodate',
            name='youtoChiiki',
            field=models.TextField(null=True),
        ),
    ]
