# Generated by Django 5.2.15 on 2026-07-08 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0012_alter_mitsuiinvestmentapartment_chimoku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(db_index=True, max_length=50, verbose_name='不動産会社コード')),
                ('property_type', models.CharField(db_index=True, max_length=50, verbose_name='物件種別')),
                ('property_id', models.IntegerField(db_index=True, verbose_name='元テーブルレコードID')),
                ('property_url', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='物件URL')),
                ('first_stage_predicted_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='一次予測理論価格')),
                ('is_first_stage_passed', models.BooleanField(default=False, verbose_name='一次スクリーニング合格フラグ')),
                ('second_stage_predicted_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='二次予測理論価格')),
                ('interior_score', models.FloatField(blank=True, null=True, verbose_name='内装クオリティスコア (1.0-5.0)')),
                ('layout_score', models.FloatField(blank=True, null=True, verbose_name='間取り評価スコア (1.0-5.0)')),
                ('investment_score', models.FloatField(blank=True, null=True, verbose_name='投資価値スコア (0-100)')),
                ('analysis_status', models.CharField(choices=[('pending', '解析待ち'), ('processing', '解析中'), ('completed', '解析完了'), ('skipped_by_budget', '予算上限スキップ'), ('failed', '解析失敗')], default='pending', max_length=30, verbose_name='画像解析ステータス')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='解析実行日時')),
            ],
            options={
                'verbose_name': '物件評価データ',
                'verbose_name_plural': '物件評価データ',
                'db_table': 'property_evaluation',
            },
        ),
        migrations.CreateModel(
            name='MunicipalPotential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=100, verbose_name='都道府県')),
                ('city', models.CharField(max_length=100, verbose_name='市区町村')),
                ('population_growth_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='人口増減率（％）')),
                ('average_income', models.IntegerField(verbose_name='1人あたり平均所得（千円）')),
            ],
            options={
                'verbose_name': '自治体ポテンシャルマスタ',
                'verbose_name_plural': '自治体ポテンシャルマスタ',
                'db_table': 'municipal_potential',
                'unique_together': {('prefecture', 'city')},
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=1000, verbose_name='画像URL')),
                ('local_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='ローカル保存パス')),
                ('category', models.CharField(choices=[('layout', '間取り図'), ('exterior', '外観'), ('interior', '内装')], max_length=50, verbose_name='画像カテゴリ')),
                ('is_cleaned', models.BooleanField(default=True, verbose_name='クレンジングフラグ')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='package.propertyevaluation', verbose_name='物件評価')),
            ],
            options={
                'verbose_name': 'クレンジング画像',
                'verbose_name_plural': 'クレンジング画像',
                'db_table': 'property_image',
            },
        ),
        migrations.CreateModel(
            name='StationPotential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(db_index=True, max_length=100, verbose_name='駅名')),
                ('railway_line', models.CharField(max_length=100, verbose_name='路線名')),
                ('passenger_volume', models.IntegerField(verbose_name='1日平均乗乗降客数')),
            ],
            options={
                'verbose_name': '駅ポテンシャルマスタ',
                'verbose_name_plural': '駅ポテンシャルマスタ',
                'db_table': 'station_potential',
                'unique_together': {('station_name', 'railway_line')},
            },
        ),
    ]
