# Generated by Django 5.2.15 on 2026-07-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0013_propertyevaluation_municipalpotential_propertyimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandPricePotential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=100, verbose_name='都道府県')),
                ('city', models.CharField(max_length=100, verbose_name='市区町村')),
                ('average_land_price', models.IntegerField(verbose_name='平均公示地価（円/㎡）')),
                ('land_use', models.CharField(choices=[('residential', '住宅地'), ('commercial', '商業地')], max_length=50, verbose_name='用途区分')),
            ],
            options={
                'verbose_name': '平均地価マスタ',
                'verbose_name_plural': '平均地価マスタ',
                'db_table': 'land_price_potential',
                'unique_together': {('prefecture', 'city', 'land_use')},
            },
        ),
    ]
