# Generated by Django 5.2.15 on 2026-07-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0014_landpricepotential'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardMapPotential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=100, verbose_name='都道府県')),
                ('city', models.CharField(max_length=100, verbose_name='市区町村')),
                ('flood_risk_level', models.IntegerField(default=0, verbose_name='浸水リスクレベル (0:低 - 4:極めて高)')),
                ('landslide_risk_level', models.IntegerField(default=0, verbose_name='土砂災害リスクレベル (0:無 - 2:高)')),
            ],
            options={
                'verbose_name': 'ハザードマップ統計マスタ',
                'verbose_name_plural': 'ハザードマップ統計マスタ',
                'db_table': 'hazard_map_potential',
                'unique_together': {('prefecture', 'city')},
            },
        ),
    ]
