# Generated by Django 5.2.15 on 2026-07-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0015_hazardmappotential'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrbanPlanningZonePotential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100, unique=True, verbose_name='用途地域名')),
                ('max_kenpei', models.IntegerField(verbose_name='上限建ぺい率（％）')),
                ('max_youseki', models.IntegerField(verbose_name='上限容積率（％）')),
            ],
            options={
                'verbose_name': '用途地域規制マスタ',
                'verbose_name_plural': '用途地域規制マスタ',
                'db_table': 'urban_planning_zone_potential',
            },
        ),
    ]
