# Generated by Django 5.2.15 on 2026-07-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0016_urbanplanningzonepotential'),
    ]

    operations = [
        migrations.AddField(
            model_name='landpricepotential',
            name='estimated_fixed_asset_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='推定固定資産税評価価格（円/㎡）'),
        ),
        migrations.AddField(
            model_name='landpricepotential',
            name='estimated_rosenka_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='推定相続税路線価（円/㎡）'),
        ),
    ]
