# Generated by Django 5.2.15 on 2026-07-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0017_landpricepotential_estimated_fixed_asset_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitsuiinvestmentapartment',
            name='kanrihi',
        ),
        migrations.RemoveField(
            model_name='mitsuiinvestmentapartment',
            name='syuzenTsumitate',
        ),
    ]
