# Generated by Django 5.2.15 on 2026-07-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0018_remove_mitsuiinvestmentapartment_kanrihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyevaluation',
            name='cash_flow',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='年間手残りキャッシュフロー'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='cashflow_score',
            field=models.FloatField(blank=True, null=True, verbose_name='キャッシュフロースコア (0-100)'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='coc_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='自己資金配当率 (CoC)'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='debt_service',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='年間元利金返済額 (ADS)'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='dscr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='債務サービスカバー率 (DSCR)'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='estimated_sekisan_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='推定積算価格'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='finance_score',
            field=models.FloatField(blank=True, null=True, verbose_name='融資適合性スコア (0-100)'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='net_operating_income',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='ネット営業純利益 (NOI)'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='sekisan_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='積算価格比率'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='total_investment_score',
            field=models.FloatField(blank=True, null=True, verbose_name='総合投資スコア (0-100)'),
        ),
    ]
