# Generated by Django 5.2.16 on 2026-07-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0019_propertyevaluation_cash_flow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyevaluation',
            name='is_slack_notified',
            field=models.BooleanField(default=False, verbose_name='Slack通知済みフラグ'),
        ),
    ]
