# Generated by Django 5.2.16 on 2026-07-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0022_athomekodate_athomemansion_homeskodate_homesmansion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyevaluation',
            name='maintenance_comment',
            field=models.TextField(blank=True, null=True, verbose_name='外観メンテナンス評価コメント'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='maintenance_score',
            field=models.FloatField(blank=True, null=True, verbose_name='外観メンテナンス状態スコア (1.0-5.0)'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='plot_shape_description',
            field=models.TextField(blank=True, null=True, verbose_name='土地の形状に関する説明・コメント'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='plot_shape_type',
            field=models.CharField(choices=[('regular', '整形地'), ('irregular', '不整形地'), ('flagpole', '旗竿地'), ('unknown', '判定不能')], default='unknown', max_length=30, verbose_name='土地の形状'),
        ),
    ]
