# Generated by Django 5.2.16 on 2026-07-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0024_athometochi_homestochi'),
    ]

    operations = [
        migrations.AddField(
            model_name='misawatochi',
            name='maguchi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='misawatochi',
            name='maguchiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='misawatochi',
            name='okuyuki',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='misawatochi',
            name='okuyukiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='misawatochi',
            name='roadDirection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='misawatochi',
            name='roadStructure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='misawatochi',
            name='roadType',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='misawatochi',
            name='roadWidth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='misawatochi',
            name='roadWidthStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mitsuitochi',
            name='maguchi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mitsuitochi',
            name='maguchiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mitsuitochi',
            name='okuyuki',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mitsuitochi',
            name='okuyukiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mitsuitochi',
            name='roadDirection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mitsuitochi',
            name='roadStructure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mitsuitochi',
            name='roadType',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mitsuitochi',
            name='roadWidth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mitsuitochi',
            name='roadWidthStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomuratochi',
            name='maguchi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='nomuratochi',
            name='maguchiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomuratochi',
            name='okuyuki',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='nomuratochi',
            name='okuyukiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomuratochi',
            name='roadDirection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomuratochi',
            name='roadStructure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomuratochi',
            name='roadType',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomuratochi',
            name='roadWidth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='nomuratochi',
            name='roadWidthStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sumifutochi',
            name='maguchi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='sumifutochi',
            name='maguchiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sumifutochi',
            name='okuyuki',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='sumifutochi',
            name='okuyukiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sumifutochi',
            name='roadDirection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sumifutochi',
            name='roadStructure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sumifutochi',
            name='roadType',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sumifutochi',
            name='roadWidth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='sumifutochi',
            name='roadWidthStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokyutochi',
            name='maguchi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tokyutochi',
            name='maguchiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokyutochi',
            name='okuyuki',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tokyutochi',
            name='okuyukiStr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokyutochi',
            name='roadDirection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokyutochi',
            name='roadStructure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokyutochi',
            name='roadType',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokyutochi',
            name='roadWidth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tokyutochi',
            name='roadWidthStr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
