# Generated by Django 5.2.16 on 2026-07-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0029_afrkodate_afrmansion_afrtochi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afrkodate',
            name='chikunengetsu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='afrkodate',
            name='douroHaba',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='afrkodate',
            name='kaisu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='afrkodate',
            name='kenpei',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='afrkodate',
            name='setsumen',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='afrkodate',
            name='tatemonoMenseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='afrkodate',
            name='tochiMenseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='afrkodate',
            name='youseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='afrmansion',
            name='chikunengetsu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='afrmansion',
            name='floorType_chijo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='afrmansion',
            name='floorType_chika',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='afrmansion',
            name='floorType_kai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='afrmansion',
            name='kanrihi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='afrmansion',
            name='senyuMenseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='afrmansion',
            name='soukosu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='afrmansion',
            name='syuzenTsumitate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='afrtochi',
            name='douroHaba',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='afrtochi',
            name='kenpei',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='afrtochi',
            name='setsumen',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='afrtochi',
            name='tochiMenseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='afrtochi',
            name='youseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
