# Generated by Django 5.2.16 on 2026-07-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0034_sumirininvestment_sumirinkodate_sumirinmansion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumirininvestment',
            name='annualRent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumirininvestment',
            name='chikunengetsu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumirininvestment',
            name='monthlyRent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumirininvestment',
            name='soukosu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumirinkodate',
            name='chikunengetsu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumirinkodate',
            name='douroHaba',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sumirinkodate',
            name='kenpei',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sumirinkodate',
            name='setsumen',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sumirinkodate',
            name='tatemonoMenseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sumirinkodate',
            name='tochiMenseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sumirinkodate',
            name='youseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sumirinmansion',
            name='chikunengetsu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumirinmansion',
            name='floorType_chijo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumirinmansion',
            name='floorType_chika',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumirinmansion',
            name='floorType_kai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumirinmansion',
            name='kanrihi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumirinmansion',
            name='kyutaishin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumirinmansion',
            name='senyuMenseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sumirinmansion',
            name='soukosu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumirinmansion',
            name='syuzenTsumitate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sumirintochi',
            name='douroHaba',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sumirintochi',
            name='kenpei',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sumirintochi',
            name='setsumen',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sumirintochi',
            name='tochiMenseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sumirintochi',
            name='youseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
