# Generated by Django 5.2.16 on 2026-07-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0035_alter_sumirininvestment_annualrent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mizuhoinvestment',
            name='annualRent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mizuhoinvestment',
            name='chikunengetsu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mizuhoinvestment',
            name='monthlyRent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mizuhoinvestment',
            name='soukosu',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
