# Generated by Django 5.2.16 on 2026-07-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0040_daikyokodate_daikyomansion_daikyotochi_keikyukodate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landpricepotential',
            name='land_price_growth_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='地価変動率（％）'),
        ),
        migrations.AddField(
            model_name='municipalpotential',
            name='income_growth_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='所得変動率（％）'),
        ),
        migrations.AddField(
            model_name='municipalpotential',
            name='total_population',
            field=models.IntegerField(blank=True, null=True, verbose_name='総人口（人）'),
        ),
    ]
