# Generated by Django 5.2.16 on 2026-07-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0041_landpricepotential_land_price_growth_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipalpotential',
            name='population_density',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='人口密度（人/㎢）'),
        ),
    ]
