# Generated by Django 5.2.16 on 2026-09-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0043_alter_afrkodate_address1_alter_afrkodate_address2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerTaskExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField(db_index=True)),
                ('task_index', models.IntegerField(default=0)),
                ('task_count', models.IntegerField(default=1)),
                ('status', models.CharField(default='RUNNING', max_length=20)),
                ('jobs_assigned', models.IntegerField(default=0)),
                ('jobs_success', models.IntegerField(default=0)),
                ('jobs_failed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crawler_task_execution',
                'unique_together': {('execution_date', 'task_index')},
            },
        ),
    ]
