# Generated by Django 5.2.16 on 2026-09-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0045_alter_afrkodate_price_alter_afrmansion_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_url', models.CharField(db_index=True, max_length=500, verbose_name='物件URL')),
                ('company', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='不動産会社コード')),
                ('property_type', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='物件種別')),
                ('old_price', models.BigIntegerField(verbose_name='改定前価格（数値）')),
                ('new_price', models.BigIntegerField(verbose_name='改定後価格（数値）')),
                ('price_diff', models.BigIntegerField(blank=True, null=True, verbose_name='価格差分（新-旧）')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='記録日時')),
            ],
            options={
                'verbose_name': '物件価格改定履歴',
                'verbose_name_plural': '物件価格改定履歴',
                'db_table': 'property_price_history',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
