# Generated by Django 5.2.16 on 2026-09-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0046_afrkodate_updatedatetime_afrmansion_updatedatetime_and_more'),
        ('package', '0046_propertypricehistory'),
    ]

    operations = [
    ]
