# Generated by Django 5.2.16 on 2026-09-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0047_merge_20260919_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePropertyUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='物件URL')),
                ('domain', models.CharField(db_index=True, max_length=100, verbose_name='ドメイン')),
                ('title', models.CharField(blank=True, default='', max_length=300, verbose_name='ページタイトル')),
                ('matched_keywords', models.JSONField(default=list, verbose_name='検知された不動産キーワード')),
                ('request_count', models.IntegerField(default=1, verbose_name='リクエスト要求回数')),
                ('status', models.CharField(choices=[('pending', '未着手'), ('developing', '開発中'), ('rejected', '対象外'), ('implemented', '実装完了')], default='pending', max_length=20, verbose_name='開発ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='初回要求日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
            ],
            options={
                'verbose_name': 'クローリング候補URL',
                'verbose_name_plural': 'クローリング候補URL一覧',
                'db_table': 'candidate_property_url',
            },
        ),
    ]
