# Generated by Django 5.2.16 on 2026-09-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0049_macroeconomicindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(db_index=True, max_length=255, verbose_name='正規化建物名')),
                ('raw_name', models.TextField(verbose_name='原本建物名')),
                ('normalized_address', models.CharField(db_index=True, max_length=255, verbose_name='正規化住所(町丁目)')),
                ('raw_address', models.TextField(verbose_name='原本所在地')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='経度')),
                ('developer_brand', models.CharField(blank=True, max_length=150, null=True, verbose_name='旧分譲主・ブランド名')),
                ('developer_tier', models.CharField(default='unknown', max_length=30, verbose_name='デベロッパー格付け')),
                ('contractor_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='施工会社')),
                ('contractor_tier', models.CharField(default='unknown', max_length=30, verbose_name='ゼネコン格付け')),
                ('structure_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='建物構造')),
                ('earthquake_resistance', models.CharField(blank=True, max_length=30, null=True, verbose_name='耐震性能')),
                ('total_units', models.IntegerField(blank=True, null=True, verbose_name='総戸数')),
                ('total_floors', models.IntegerField(blank=True, null=True, verbose_name='地上総階数')),
                ('built_year', models.IntegerField(blank=True, null=True, verbose_name='建築年')),
                ('built_month', models.IntegerField(blank=True, null=True, verbose_name='建築月')),
                ('elevator_available', models.BooleanField(blank=True, null=True, verbose_name='エレベーター有無')),
                ('elevator_count', models.IntegerField(blank=True, null=True, verbose_name='エレベーター基数')),
                ('hallway_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='共用廊下(内廊下/外廊下)')),
                ('garbage_disposal_24h', models.BooleanField(blank=True, null=True, verbose_name='24時間ゴミ出し可否')),
                ('management_company', models.CharField(blank=True, max_length=150, null=True, verbose_name='管理会社名')),
                ('management_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='管理形態')),
                ('manager_working_style', models.CharField(blank=True, max_length=50, null=True, verbose_name='管理員勤務形態')),
                ('repair_reserve_score', models.FloatField(blank=True, null=True, verbose_name='修繕積立金・管理組合健全性スコア')),
                ('shared_facilities_json', models.TextField(blank=True, null=True, verbose_name='共用施設リストJSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '建物マスタ',
                'verbose_name_plural': '建物マスタ',
                'db_table': 'building_master',
                'unique_together': {('normalized_name', 'normalized_address')},
            },
        ),
    ]
