# Generated by Django 5.2.16 on 2026-09-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0050_kenbiyainvestmentbuilding_kenbiyakodate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroEconomicIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(db_index=True, max_length=7, unique=True, verbose_name='対象年月 (YYYY-MM)')),
                ('repi_mansion', models.FloatField(blank=True, null=True, verbose_name='国交省 不動産価格指数(マンション)')),
                ('repi_kodate', models.FloatField(blank=True, null=True, verbose_name='国交省 不動産価格指数(戸建)')),
                ('repi_tochi', models.FloatField(blank=True, null=True, verbose_name='国交省 不動産価格指数(住宅地)')),
                ('jgb_10y_yield', models.FloatField(blank=True, null=True, verbose_name='新発10年物国債利回り (%)')),
                ('mortgage_fixed_rate', models.FloatField(blank=True, null=True, verbose_name='フラット35等固定金利基準 (%)')),
                ('nikkei_225', models.FloatField(blank=True, null=True, verbose_name='日経平均株価月末終値 (円)')),
                ('tse_reit_index', models.FloatField(blank=True, null=True, verbose_name='東証REIT指数月末終値 (pt)')),
                ('construction_cost_index', models.FloatField(blank=True, null=True, verbose_name='建設物価指数(RC/住宅)')),
                ('cpi_core', models.FloatField(blank=True, null=True, verbose_name='消費者物価指数コア(2020年=100)')),
            ],
            options={
                'verbose_name': 'マクロ経済指標マスタ',
                'verbose_name_plural': 'マクロ経済指標マスタ',
                'db_table': 'macro_economic_index',
            },
        ),
    ]
