# Generated by Django 5.2.16 on 2026-09-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0050_buildingmaster'),
        ('package', '0050_kenbiyainvestmentbuilding_kenbiyakodate_and_more'),
    ]

    operations = [
    ]
