# Generated by Django 5.2.17 on 2026-09-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ('package', '0052_afrkodate_chidai_afrkodate_chidaistr_and_more'),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name='propertyevaluation',
            name='bath_type',
            field=models.CharField(default='unknown', max_length=20, verbose_name='浴室種別'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='demolition_difficulty',
            field=models.CharField(choices=[('low', '容易 (重機進入容易)'), ('medium', '通常'), ('high', '困難 (狭小手壊し要)')], default='medium', max_length=20, verbose_name='解体・重機進入難易度'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='exposed_pipes_risk',
            field=models.BooleanField(blank=True, null=True, verbose_name='露出老朽化配管サイン有無'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='foundation_crack_risk',
            field=models.BooleanField(blank=True, null=True, verbose_name='基礎構造クラック有無'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='frontage_length_est',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='推定間口長 (m)'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='gas_type',
            field=models.CharField(default='unknown', max_length=20, verbose_name='ガス種別'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='ground_elevation_diff_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='道路宅地高低差 (m)'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='has_elevator',
            field=models.BooleanField(blank=True, null=True, verbose_name='エレベーター有無'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='has_private_road_burden',
            field=models.BooleanField(default=False, verbose_name='私道負担・持分なしフラグ'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='indoor_washing_machine_space',
            field=models.CharField(choices=[('indoor', '室内'), ('outdoor', '外置き (バルコニー等)'), ('unknown', '不明')], default='unknown', max_length=20, verbose_name='洗濯機置場'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='is_as_is_condition',
            field=models.BooleanField(default=False, verbose_name='契約不適合免責フラグ'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='is_boundary_unspecified',
            field=models.BooleanField(default=False, verbose_name='境界非明示フラグ'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='is_old_earthquake_standard',
            field=models.BooleanField(blank=True, null=True, verbose_name='旧耐震基準判定'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='is_psychological_defect',
            field=models.BooleanField(default=False, verbose_name='心理的瑕疵フラグ'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='is_stair_only_3f_plus',
            field=models.BooleanField(blank=True, null=True, verbose_name='3階以上階段物件フラグ'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='is_sublease',
            field=models.BooleanField(default=False, verbose_name='サブリース中フラグ'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='is_unbuildable',
            field=models.BooleanField(default=False, verbose_name='再建築不可フラグ'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='is_urbanization_control_area',
            field=models.BooleanField(default=False, verbose_name='市街化調整区域フラグ'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='nta_irregular_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='国税庁不整形地補正率'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='passage_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='旗竿地通路幅 (m)'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='renovation_budget_tier',
            field=models.CharField(choices=[('tier_none', '不要 (0円/美室)'), ('tier_light', '軽微 (〜100万円/表層)'), ('tier_medium', '標準 (〜300万円/水回り一部)'), ('tier_heavy', '大規模 (〜600万円/水回り全交換)'), ('tier_full', 'フルリノベ (1000万円超/スケルトン)')], default='tier_medium', max_length=30, verbose_name='想定リフォーム費用規模'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='retaining_wall_risk',
            field=models.CharField(choices=[('none', '擁壁なし/平坦'), ('rc_legal', '適法RC擁壁'), ('stone_masonry', '間知石/玉石積み'), ('two_tier_illegal', '二段擁壁/危険擁壁')], default='none', max_length=30, verbose_name='擁壁リスク種別'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='road_width_est',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='推定前面道路幅員 (m)'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='sewage_type',
            field=models.CharField(default='unknown', max_length=20, verbose_name='下水種別'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='shadow_area_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='かげ地割合 (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='shape_score_100',
            field=models.FloatField(blank=True, null=True, verbose_name='総合画地幾何スコア (0-100点)'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='stair_steepness',
            field=models.CharField(choices=[('normal', '通常勾配'), ('steep', '急勾配 (昭和階段)'), ('unknown', '不明')], default='unknown', max_length=20, verbose_name='階段勾配'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='utility_pole_risk',
            field=models.CharField(choices=[('none', 'なし'), ('pole', '敷地内電柱あり'), ('guy_wire', '黄色支線あり')], default='none', max_length=20, verbose_name='敷地内電柱・支線リスク'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='water_leak_risk',
            field=models.BooleanField(blank=True, null=True, verbose_name='軒天・漏水サイン有無'),
        ),
        migrations.AlterField(
            model_name='odakyuinvestment',
            name='annualRent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odakyuinvestment',
            name='chikunengetsu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odakyuinvestment',
            name='monthlyRent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odakyuinvestment',
            name='soukosu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='category',
            field=models.CharField(choices=[('layout', '間取り図'), ('plot_plan', '区画図・敷地配置図'), ('exterior', '外観'), ('interior', '内装')], max_length=50, verbose_name='画像カテゴリ'),
        ),
    ]
