# ruff: noqa: RUF012
# Generated by Django on 2026-10-04 (Issue #665)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0058_deduplicate_and_enforce_unique_pageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyevaluation',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='公開中フラグ'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='delisted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='掲載終了検知日時'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='needs_parser_fix',
            field=models.BooleanField(db_index=True, default=False, verbose_name='パーサー改修必要フラグ'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='needs_recrawl',
            field=models.BooleanField(db_index=True, default=False, verbose_name='再クローリング対象フラグ'),
        ),
        migrations.AddField(
            model_name='propertyevaluation',
            name='data_quality_issue',
            field=models.TextField(blank=True, default='', verbose_name='データ不正・欠損理由'),
        ),
    ]
