# ruff: noqa: RUF012
# Generated by Django 5.2.17 on 2026-10-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0059_propertyevaluation_delisted_and_recrawl_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomurainvestmentkodate',
            name='madori',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='nomurainvestmentapartment',
            name='soukosu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smtrcinvestment',
            name='annualRent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smtrcinvestment',
            name='chikunengetsu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smtrcinvestment',
            name='monthlyRent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smtrcinvestment',
            name='soukosu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smtrckodate',
            name='kenpei',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='smtrckodate',
            name='tatemonoMenseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='smtrckodate',
            name='tochiMenseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='smtrckodate',
            name='youseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='smtrcmansion',
            name='chikunengetsu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smtrcmansion',
            name='floorType_chijo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smtrcmansion',
            name='floorType_chika',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smtrcmansion',
            name='floorType_kai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smtrcmansion',
            name='kanrihi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smtrcmansion',
            name='kyutaishin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smtrcmansion',
            name='senyuMenseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='smtrcmansion',
            name='soukosu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smtrcmansion',
            name='syuzenTsumitate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smtrctochi',
            name='douroHaba',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='smtrctochi',
            name='kenpei',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='smtrctochi',
            name='setsumen',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='smtrctochi',
            name='tochiMenseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='smtrctochi',
            name='youseki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
