# ruff: noqa: RUF012
# Generated by Django 5.2.17 on 2026-10-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0060_nomurainvestmentkodate_madori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomurakodate',
            name='madori',
            field=models.TextField(blank=True, default=''),
        ),
    ]
