"""
ML 特徴量セット定義 (Issue #713, Epic #710)
"""

FEATURE_SETS = {
    "mansion": {
        "first": [
            "area", "chikunen", "walk_min", "kanrihi", "syuzen",
            "pop_growth", "income", "passenger_volume", "average_land_price",
            "estimated_rosenka_price", "estimated_fixed_asset_price",
            "cost_approach_value", "mkt_comparison_value", "income_approach_value",
            "is_shin_taishin", "flood_risk_level", "landslide_risk_level",
            "max_youseki", "max_kenpei", "max_building_area", "max_floor_area",
            "kagechi_ratio", "total_population", "income_growth_rate", "land_price_growth_rate",
            "effective_walk_min", "population_density", "kouzou_lifespan_ratio",
            "floor_number", "total_floors", "floor_ratio", "is_top_floor", "is_first_floor",
            "room_count", "has_ldk", "is_studio",
            "kouzou_durability_rank", "kouzou_fireproof_score", "is_rc_or_src", "is_wood",
            "company_tier", "is_major_company",
            "is_residential_zone", "is_commercial_zone", "is_industrial_zone", "zone_rank",
            "is_shigaika_chousei", "is_saikenchiku_fuka", "rights_ratio",
            "potential_floor_area", "scale_discount",
            "zone_max_kenpei", "zone_max_youseki",
            "time_diff_months", "macro_repi", "macro_jgb_10y", "macro_nikkei", "macro_reit", "macro_construction_cost", "is_legacy_data"
        ],
        "second": [
            "area", "chikunen", "walk_min", "kanrihi", "syuzen",
            "pop_growth", "income", "passenger_volume", "average_land_price",
            "estimated_rosenka_price", "estimated_fixed_asset_price",
            "cost_approach_value", "mkt_comparison_value", "income_approach_value",
            "is_shin_taishin", "flood_risk_level", "landslide_risk_level",
            "max_youseki", "max_kenpei", "max_building_area", "max_floor_area",
            "kagechi_ratio", "total_population", "income_growth_rate", "land_price_growth_rate",
            "effective_walk_min", "population_density", "kouzou_lifespan_ratio",
            "floor_number", "total_floors", "floor_ratio", "is_top_floor", "is_first_floor",
            "room_count", "has_ldk", "is_studio",
            "kouzou_durability_rank", "kouzou_fireproof_score", "is_rc_or_src", "is_wood",
            "company_tier", "is_major_company",
            "is_residential_zone", "is_commercial_zone", "is_industrial_zone", "zone_rank",
            "interior_score", "layout_score",
            "is_shigaika_chousei", "is_saikenchiku_fuka", "rights_ratio",
            "potential_floor_area", "scale_discount",
            "zone_max_kenpei", "zone_max_youseki",
            "time_diff_months", "macro_repi", "macro_jgb_10y", "macro_nikkei", "macro_reit", "macro_construction_cost", "is_legacy_data"
        ]
    },
    "kodate": {
        "first": [
            "area", "tochi_menseki", "chikunen", "walk_min",
            "pop_growth", "income", "passenger_volume", "average_land_price",
            "estimated_rosenka_price", "estimated_fixed_asset_price",
            "digest_volume_ratio", "surplus_volume_potential", "non_conforming_flag",
            "cost_approach_value", "mkt_comparison_value", "income_approach_value",
            "is_shin_taishin", "flood_risk_level", "landslide_risk_level",
            "max_youseki", "max_kenpei",
            "maguchi", "road_width", "setback_ratio", "actual_volume_limit",
            "volume_digest_factor", "road_condition_factor", "frontage_penalty_factor", "residual_land_value",
            "max_building_area", "max_floor_area", "kagechi_ratio",
            "total_population", "income_growth_rate", "land_price_growth_rate",
            "effective_walk_min", "population_density", "kouzou_lifespan_ratio",
            "road_direction_angle", "sunlight_score", "is_south_facing",
            "road_type_score", "is_public_road", "is_private_road",
            "road_structure_score", "is_corner_lot", "is_double_sided_road",
            "chimoku_score", "is_residential_chimoku",
            "room_count", "has_ldk", "total_floors",
            "kouzou_durability_rank", "kouzou_fireproof_score", "is_rc_or_src", "is_wood",
            "company_tier", "is_major_company",
            "is_residential_zone", "is_commercial_zone", "is_industrial_zone", "zone_rank",
            "shape_type_code", "is_regular_shape",
            "is_shigaika_chousei", "is_saikenchiku_fuka", "rights_ratio",
            "potential_floor_area", "scale_discount",
            "plot_shadow_ratio", "plot_aspect_ratio", "plot_effective_ratio", "plot_shape_penalty",
            "plot_mic_diameter", "plot_bottleneck_width", "plot_solidity", "plot_compactness",
            "plot_nta_discount", "plot_acute_angles", "plot_flagpole_ratio", "plot_shape_grade_num",
            "plot_shape_score_100",
            "zone_max_kenpei", "zone_max_youseki",
            "time_diff_months", "macro_repi", "macro_jgb_10y", "macro_nikkei", "macro_reit", "macro_construction_cost", "is_legacy_data"
        ],
        "second": [
            "area", "tochi_menseki", "chikunen", "walk_min",
            "pop_growth", "income", "passenger_volume", "average_land_price",
            "estimated_rosenka_price", "estimated_fixed_asset_price",
            "digest_volume_ratio", "surplus_volume_potential", "non_conforming_flag",
            "cost_approach_value", "mkt_comparison_value", "income_approach_value",
            "is_shin_taishin", "flood_risk_level", "landslide_risk_level",
            "max_youseki", "max_kenpei",
            "maguchi", "road_width", "setback_ratio", "actual_volume_limit",
            "volume_digest_factor", "road_condition_factor", "frontage_penalty_factor", "residual_land_value",
            "max_building_area", "max_floor_area", "kagechi_ratio",
            "total_population", "income_growth_rate", "land_price_growth_rate",
            "effective_walk_min", "population_density", "kouzou_lifespan_ratio",
            "road_direction_angle", "sunlight_score", "is_south_facing",
            "road_type_score", "is_public_road", "is_private_road",
            "road_structure_score", "is_corner_lot", "is_double_sided_road",
            "chimoku_score", "is_residential_chimoku",
            "room_count", "has_ldk", "total_floors",
            "kouzou_durability_rank", "kouzou_fireproof_score", "is_rc_or_src", "is_wood",
            "company_tier", "is_major_company",
            "is_residential_zone", "is_commercial_zone", "is_industrial_zone", "zone_rank",
            "shape_type_code", "is_regular_shape",
            "interior_score", "layout_score",
            "is_shigaika_chousei", "is_saikenchiku_fuka", "rights_ratio",
            "potential_floor_area", "scale_discount",
            "plot_shadow_ratio", "plot_aspect_ratio", "plot_effective_ratio", "plot_shape_penalty",
            "plot_mic_diameter", "plot_bottleneck_width", "plot_solidity", "plot_compactness",
            "plot_nta_discount", "plot_acute_angles", "plot_flagpole_ratio", "plot_shape_grade_num",
            "plot_shape_score_100",
            "zone_max_kenpei", "zone_max_youseki",
            "time_diff_months", "macro_repi", "macro_jgb_10y", "macro_nikkei", "macro_reit", "macro_construction_cost", "is_legacy_data"
        ]
    },
    "apartment": {
        "first": [
            "area", "tochi_menseki", "chikunen", "walk_min",
            "pop_growth", "income", "passenger_volume", "average_land_price",
            "estimated_rosenka_price", "estimated_fixed_asset_price",
            "digest_volume_ratio", "surplus_volume_potential", "non_conforming_flag",
            "gross_yield", "annual_rent",
            "cost_approach_value", "mkt_comparison_value", "income_approach_value",
            "is_shin_taishin", "flood_risk_level", "landslide_risk_level",
            "max_youseki", "max_kenpei",
            "maguchi", "road_width", "setback_ratio", "actual_volume_limit",
            "volume_digest_factor", "road_condition_factor", "frontage_penalty_factor", "residual_land_value",
            "max_building_area", "max_floor_area", "kagechi_ratio",
            "total_population", "income_growth_rate", "land_price_growth_rate",
            "effective_walk_min", "population_density", "kouzou_lifespan_ratio",
            "road_direction_angle", "sunlight_score", "is_south_facing",
            "road_type_score", "is_public_road", "is_private_road",
            "road_structure_score", "is_corner_lot", "is_double_sided_road",
            "chimoku_score", "is_residential_chimoku",
            "total_floors",
            "kouzou_durability_rank", "kouzou_fireproof_score", "is_rc_or_src", "is_wood",
            "company_tier", "is_major_company",
            "is_residential_zone", "is_commercial_zone", "is_industrial_zone", "zone_rank",
            "shape_type_code", "is_regular_shape",
            "is_shigaika_chousei", "is_saikenchiku_fuka", "rights_ratio",
            "potential_floor_area", "scale_discount",
            "plot_shadow_ratio", "plot_aspect_ratio", "plot_effective_ratio", "plot_shape_penalty",
            "plot_mic_diameter", "plot_bottleneck_width", "plot_solidity", "plot_compactness",
            "plot_nta_discount", "plot_acute_angles", "plot_flagpole_ratio", "plot_shape_grade_num",
            "plot_shape_score_100",
            "zone_max_kenpei", "zone_max_youseki",
            "time_diff_months", "macro_repi", "macro_jgb_10y", "macro_nikkei", "macro_reit", "macro_construction_cost", "is_legacy_data"
        ],
        "second": [
            "area", "tochi_menseki", "chikunen", "walk_min",
            "pop_growth", "income", "passenger_volume", "average_land_price",
            "estimated_rosenka_price", "estimated_fixed_asset_price",
            "digest_volume_ratio", "surplus_volume_potential", "non_conforming_flag",
            "gross_yield", "annual_rent",
            "cost_approach_value", "mkt_comparison_value", "income_approach_value",
            "is_shin_taishin", "flood_risk_level", "landslide_risk_level",
            "max_youseki", "max_kenpei",
            "maguchi", "road_width", "setback_ratio", "actual_volume_limit",
            "volume_digest_factor", "road_condition_factor", "frontage_penalty_factor", "residual_land_value",
            "max_building_area", "max_floor_area", "kagechi_ratio",
            "total_population", "income_growth_rate", "land_price_growth_rate",
            "effective_walk_min", "population_density", "kouzou_lifespan_ratio",
            "road_direction_angle", "sunlight_score", "is_south_facing",
            "road_type_score", "is_public_road", "is_private_road",
            "road_structure_score", "is_corner_lot", "is_double_sided_road",
            "chimoku_score", "is_residential_chimoku",
            "total_floors",
            "kouzou_durability_rank", "kouzou_fireproof_score", "is_rc_or_src", "is_wood",
            "company_tier", "is_major_company",
            "is_residential_zone", "is_commercial_zone", "is_industrial_zone", "zone_rank",
            "shape_type_code", "is_regular_shape",
            "interior_score", "layout_score",
            "is_shigaika_chousei", "is_saikenchiku_fuka", "rights_ratio",
            "potential_floor_area", "scale_discount",
            "plot_shadow_ratio", "plot_aspect_ratio", "plot_effective_ratio", "plot_shape_penalty",
            "plot_mic_diameter", "plot_bottleneck_width", "plot_solidity", "plot_compactness",
            "plot_nta_discount", "plot_acute_angles", "plot_flagpole_ratio", "plot_shape_grade_num",
            "plot_shape_score_100",
            "zone_max_kenpei", "zone_max_youseki",
            "time_diff_months", "macro_repi", "macro_jgb_10y", "macro_nikkei", "macro_reit", "macro_construction_cost", "is_legacy_data"
        ]
    },
    "tochi": {
        "first": [
            "area", "tochi_menseki", "walk_min",
            "pop_growth", "income", "passenger_volume", "average_land_price",
            "estimated_rosenka_price", "estimated_fixed_asset_price",
            "cost_approach_value", "mkt_comparison_value", "income_approach_value",
            "flood_risk_level", "landslide_risk_level",
            "max_youseki", "max_kenpei",
            "maguchi", "road_width", "setback_ratio", "actual_volume_limit",
            "volume_digest_factor", "road_condition_factor", "frontage_penalty_factor", "residual_land_value",
            "max_building_area", "max_floor_area", "kagechi_ratio",
            "total_population", "income_growth_rate", "land_price_growth_rate",
            "effective_walk_min", "population_density",
            "road_direction_angle", "sunlight_score", "is_south_facing",
            "road_type_score", "is_public_road", "is_private_road",
            "road_structure_score", "is_corner_lot", "is_double_sided_road",
            "chimoku_score", "is_residential_chimoku",
            "company_tier", "is_major_company",
            "is_residential_zone", "is_commercial_zone", "is_industrial_zone", "zone_rank",
            "shape_type_code", "is_regular_shape",
            "is_shigaika_chousei", "is_saikenchiku_fuka", "rights_ratio",
            "potential_floor_area", "scale_discount",
            "is_furuya", "has_demolition_condition", "furuya_demolition_cost", "furuya_usable_value", "furuya_option_value",
            "plot_shadow_ratio", "plot_aspect_ratio", "plot_effective_ratio", "plot_shape_penalty",
            "plot_mic_diameter", "plot_bottleneck_width", "plot_solidity", "plot_compactness",
            "plot_nta_discount", "plot_acute_angles", "plot_flagpole_ratio", "plot_shape_grade_num",
            "plot_shape_score_100",
            "zone_max_kenpei", "zone_max_youseki",
            "time_diff_months", "macro_repi", "macro_jgb_10y", "macro_nikkei", "macro_reit", "macro_construction_cost", "is_legacy_data"
        ],
        "second": [
            "area", "tochi_menseki", "walk_min",
            "pop_growth", "income", "passenger_volume", "average_land_price",
            "estimated_rosenka_price", "estimated_fixed_asset_price",
            "cost_approach_value", "mkt_comparison_value", "income_approach_value",
            "flood_risk_level", "landslide_risk_level",
            "max_youseki", "max_kenpei",
            "maguchi", "road_width", "setback_ratio", "actual_volume_limit",
            "volume_digest_factor", "road_condition_factor", "frontage_penalty_factor", "residual_land_value",
            "max_building_area", "max_floor_area", "kagechi_ratio",
            "total_population", "income_growth_rate", "land_price_growth_rate",
            "effective_walk_min", "population_density",
            "road_direction_angle", "sunlight_score", "is_south_facing",
            "road_type_score", "is_public_road", "is_private_road",
            "road_structure_score", "is_corner_lot", "is_double_sided_road",
            "chimoku_score", "is_residential_chimoku",
            "company_tier", "is_major_company",
            "is_residential_zone", "is_commercial_zone", "is_industrial_zone", "zone_rank",
            "shape_type_code", "is_regular_shape",
            "interior_score", "layout_score",
            "is_shigaika_chousei", "is_saikenchiku_fuka", "rights_ratio",
            "potential_floor_area", "scale_discount",
            "is_furuya", "has_demolition_condition", "furuya_demolition_cost", "furuya_usable_value", "furuya_option_value",
            "plot_shadow_ratio", "plot_aspect_ratio", "plot_effective_ratio", "plot_shape_penalty",
            "plot_mic_diameter", "plot_bottleneck_width", "plot_solidity", "plot_compactness",
            "plot_nta_discount", "plot_acute_angles", "plot_flagpole_ratio", "plot_shape_grade_num",
            "plot_shape_score_100",
            "zone_max_kenpei", "zone_max_youseki",
            "time_diff_months", "macro_repi", "macro_jgb_10y", "macro_nikkei", "macro_reit", "macro_construction_cost", "is_legacy_data"
        ]
    }
}
