name: GCP Auth Test

on:
  push:
    branches: [ 'feature/gcp-auth-test' ]

permissions:
  id-token: write
  contents: read

jobs:
  auth-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Test Auth (gcloud)
        run: |
          gcloud auth list
          gcloud projects list
